openapi: 3.0.3

info:
  title: Flights API
  description: This is the API specification for the Booking 2026 AC.
  version: 1.0.0

servers:
  - url: 'https://localhost:8080/api'

tags:
  - name: Flights
    description: Operations related to flights
  - name: Airports
    description: Operations related to airports

paths:
  /flights:
    get:
      tags:
        - Flights
      summary: Get all flights
      description: Get a list of flights
      parameters:
        - in: query
          name: flightNumber
          schema:
            type: string
          description: The flight number
        - in: query
          name: origin
          schema:
            type: string
          description: The flight origin
        - in: query
          name: destination
          schema:
            type: string
          description: The flight destination
        - in: query
          name: airline
          schema:
            type: string
          description: The flight airline
      responses:
        '200':
          description: Flights found
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                  - $ref: '#/components/schemas/Flight'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid query
        '404':
          description: Companies not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Flights not found
        '500':
          description: Internal server error
    post:
      tags:
        - Flights
      summary: Create a new flight
      description: Create a new flight
      requestBody:
        $ref: '#/components/requestBodies/CompanyPostRequest'
      responses:
        '201':
          description: Flight created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flight'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid parameters
        '500':
          description: Internal server error
  /flights/{id}:
    get:
      tags:
        - Flights
      summary: Get a flight by id
      description: Gets a flight from the database by its id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flight'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid ID
        '404':
          description: Flight not found
        '500':
          description: Internal server error
    delete:
      tags:
        - Flights
      summary: Delete a flight
      description: Deletes a flight from the database
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          description: ID of the flight to delete
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flight'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Bad request
        '404':
          description: Flight not found
        '500':
          description: Internal server error
  /flights/{id}/book:
    patch:
      tags:
        - Flights
      summary: Book a seat for a flight
      description: Reduces the seat count by 1 for a specific flight
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          description: ID of the flight to book
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flight'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Flight cannot be booked query
        '404':
          description: Flight not found
        '500':
          description: Internal server error

  /airports:
    get:
      tags:
        - Airports
      summary: Get airports
      description: Get a list of airports
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: The airport name, or code or city
      responses:
        '200':
          description: Airports found
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/Airport'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid query
        '404':
          description: Companies not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Airports not found
        '500':
          description: Internal server error

components:
  schemas:
    Flight:
      type: object
      description: Flight information.
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          description: Database-generated unique identifier of the flight.
        flightNumber:
          type: string
          description: Airline flight number (e.g. "IB3171").
          example: "IB3171"
        airline:
          type: string
          description: Airline operating the flight.
          example: "Iberia"
        origin:
          type: string
          description: IATA code or name of the origin airport.
          example: "MAD"
        destination:
          type: string
          description: IATA code or name of the destination airport.
          example: "LHR"
        departureTime:
          type: string
          format: date-time
          nullable: true
          description: >
            Scheduled local departure time (without explicit time zone in the value;
            use departureTimezone to interpret it).
          example: "2025-03-10T10:30:00"
        arrivalTime:
          type: string
          format: date-time
          nullable: true
          description: >
            Scheduled local arrival time (without explicit time zone in the value;
            use arrivalTimezone to interpret it).
          example: "2025-03-10T12:05:00"
        departureTimezone:
          type: string
          nullable: true
          description: IANA time zone of the departure airport.
          example: "Europe/Madrid"
        arrivalTimezone:
          type: string
          nullable: true
          description: IANA time zone of the arrival airport.
          example: "Europe/London"
        duration:
          type: integer
          format: int32
          description: Flight duration in minutes.
          example: 95
          minimum: 0
        price:
          type: integer
          format: int32
          description: Price in minor units (e.g. cents) to avoid floating point issues.
          example: 15999
          minimum: 0
        currency:
          type: string
          description: ISO 4217 currency code.
          example: "EUR"
        availableSeats:
          type: integer
          format: int32
          description: Number of seats currently available for booking.
          example: 12
          minimum: 0
      required:
        - flightNumber
        - airline
        - origin
        - destination
    Airport:
      type: object
      description: Airport information.
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          description: Database-generated unique identifier of the airport.
        code:
          type: string
          description: Three-letter airport code.
          example: "AMS"
        name:
          type: string
          description: Airport name.
          example: "Amsterdam Schiphol Airport"
        city:
          type: string
          description: City of the airport.
          example: "Amsterdam"
        country:
          type: string
          description: Country of the airport.
          example: "The Netherlands"
        timezone:
          type: string
          description: Airport's timezone.
          example: "UTC"



  requestBodies:
    CompanyPostRequest:
      description: Company details
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                example: Paro Software
              phone:
                type: string
                format: phone
                example: +31600111222
              address:
                type: string
                example: 123 Main Street
              zipcode:
                type: string
                format: zipcode
                example: 1234AB
              city:
                type: string
                example: Heemskerk
              country:
                type: string
                example: Netherlands
              portal_id:
                type: integer
                format: int64
                example: 1

    CompanyPutRequest:
      description: Company details to update
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              phone:
                type: string
                format: phone
                example: +31600111222
              address:
                type: string
                example: 123 Main Street
              zipcode:
                type: string
                format: zipcode
                example: 1234AB
              city:
                type: string
                example: Heemskerk
              country:
                type: string
                example: Netherlands
